plugins {
    id 'com.android.application'
}

android {
    namespace 'com.demo.autolock'
    compileSdk 35

    defaultConfig {
        applicationId "com.demo.autolock"
        minSdk 28
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    packaging {
        resources {
            excludes += [
                "/META-INF/*.kotlin_module",
                "/META-INF/*.version",
                "**/kotlin/**",
                "DebugProbesKt.bin"
            ]
        }
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:102.0.0'
}
